In [52]:
class Passenger():
    def __init__(self, orig_idx, dest_idx, arr_time):
        self.orig_idx = orig_idx
        self.dest_idx = dest_idx
        self.arr_time = arr_time
        self.board_time = 0.0
        self.alight_time = 0.0
        self.denied = 0
        self.wait_time = 0.0

In [5]:
class Stop():
    def __init__(self, stop_id):
        self.stop_id = stop_id
        self.last_bus_time = []
        self.prev_denied = 0
        self.passengers = []

In [6]:
import numpy as np

In [21]:
TOT_SIM_TIME = 3 # HOURS
START_SIM_TIME = 20000
STOPS = ['386','388', '390']

In [10]:
np.random.uniform(0, 1, size=(3,3))

array([[0.15278215, 0.81502496, 0.65725334],
       [0.68313201, 0.23441016, 0.66960119],
       [0.80352859, 0.93631478, 0.12271107]])

In [16]:
OD = np.random.uniform(1,3,size=(3,3))

In [17]:
OD

array([[1.94364219, 1.97017472, 1.83279999],
       [2.40279515, 1.06953116, 1.35067768],
       [2.4346653 , 2.42243987, 1.52614719]])

In [19]:
np.random.exponential(3600/10, size=10).mean()

390.5684878438591

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a,b, axis=-1)
c

array([1, 2, 3, 4, 5, 6])

In [54]:
stops = []
for i in range(len(STOPS)):
    stops.append(Stop(STOPS[i]))
    for j in range(i+1, len(STOPS)):
        od_rate = OD[i,j]
        max_size = int(od_rate*TOT_SIM_TIME*2)
        temp_pax_interarr_times = np.random.exponential(3600/(od_rate), size=max_size)
        temp_pax_arr_times = np.cumsum(temp_pax_interarr_times)
        temp_pax_arr_times = temp_pax_arr_times[temp_pax_arr_times <= TOT_SIM_TIME*3600]
        temp_pax_arr_times += START_SIM_TIME
        for t in temp_pax_arr_times:
            stops[i].passengers.append(Passenger(i,j,t))

In [55]:
stops[0]

In [56]:
stops[0].passengers

In [57]:
for p in stops[0].passengers:
    print(p.arr_time)
    print(stops[p.dest_idx].stop_id)

20138.050991768905
388
20358.428442290162
388
22588.773243275493
388
23711.641149933916
388
28181.601470667367
388
29212.061469964057
388
22673.88438227299
390
22946.17747033211
390
23336.937214723905
390
28238.36697336445
390
28841.50987370777
390


In [ ]:
a={(1,2):3}

In [45]:
a

{(1, 2): 3}